DB_OK = ""
MISSING_PARAMETERS = "Not enough parameters"
EMAIL_ALREADY_REGISTERED = "Email already registered"
NO_USER_WITH_ID = "There is no User with this ID"
CHIP_ALREADY_EXISTS = "A chip with this ICCID already exists"
NO_CHIP_WITH_ID = "There is no chip with this ID"
